version: "3"

services:
  telegram:
    build:
      context: .
      dockerfile: .docker/Dockerfile-telegram
    command: python main.py
    working_dir: /usr/src
    volumes:
      - ./telegram:/usr/src
      - ./protos:/protos
    ports:
      - 50053:50053
    expose:
      - 50053
    networks:
      - main_network

  user:
    build:
      context: .
      dockerfile: .docker/Dockerfile-user
    volumes:
      - ./user:/go/src/github.com/alexkarpovich/micro-svc
      - ./protos:/protos
    ports:
      - 50052:50052
    expose:
      - 50052
    networks:
      - main_network

  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    networks:
      - main_network

  ui:
    build:
      context: .
      dockerfile: .docker/Dockerfile-ui
    command: npm run hmr
    ports:
      - '3000:3000'
    volumes:
      - ./ui:/usr/src/app
    networks:
      - main_network

volumes:
  postgres_data:

networks:
  main_network:
